name: Publish Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-image:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GH_PAT }}"

      - name: "Set lower case repository name"
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: "Build and publish Docker image"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64,linux/arm/v8"
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest
            ghcr.io/${{ env.REPO_LC }}:${{ github.ref_name }}
